### ISSUE TITLE
create one instance

### ISSUE THREAD

**Issue by wwt12138** [nullqwertyuiop/tweet-crawler#3]
i try to create one instance and come across the problem :
Traceback (most recent call last):
  File "d:\software\ANACONDA\envs\twitter\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\software\ANACONDA\envs\twitter\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "D:\code\tweet-crawler-main\tweet-crawler-main\test.py", line 36, in <module>
    asyncio.run(main(url))
  File "d:\software\ANACONDA\envs\twitter\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "d:\software\ANACONDA\envs\twitter\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\software\ANACONDA\envs\twitter\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\code\tweet-crawler-main\tweet-crawler-main\test.py", line 32, in main
    await crawler.run()
  File "D:\code\tweet-crawler-main\tweet-crawler-main\test.py", line 11, in run
    await self.page.goto(self.url)
  File "d:\software\ANACONDA\envs\twitter\Lib\site-packages\playwright\async_api\_generated.py", line 8810, in goto
    await self._impl_obj.goto(
  File "d:\software\ANACONDA\envs\twitter\Lib\site-packages\playwright\_impl\_page.py", line 524, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\software\ANACONDA\envs\twitter\Lib\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "d:\software\ANACONDA\envs\twitter\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\software\ANACONDA\envs\twitter\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.

the instance :
import asyncio
from playwright.async_api import async_playwright

class TwitterStatusCrawler:
    def __init__(self, page, url):
        self.page = page
        self.url = url

    async def run(self):
        # 访问推文页面
        await self.page.goto(self.url)
        
        # 等待页面加载完成
        await self.page.wait_for_load_state('networkidle')

        # 这里可以添加更多的操作，比如抓取推文内容
        # 例如：获取推文的文本
        tweet_text = await self.page.text_content('div[data-testid="tweetText"]')
        print(f"Tweet Text: {tweet_text}")

        # 根据需要添加其他抓取逻辑

# URL of the tweet to crawl
url = "https://x.com/elonmusk/status/1851277287221817514"

async def main(url):
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        context = await browser.new_context()
        page = await context.new_page()
        crawler = TwitterStatusCrawler(page, url)
        await crawler.run()
        await browser.close()

if __name__ == "__main__":
    asyncio.run(main(url))

**Comment by nullqwertyuiop** [comment]
Hi there,

Thank you for bringing this issue to our attention.

The exception `playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded` generally indicates that the page took too long to load. In this case, it seems that your computer might be having trouble reaching Twitter's server. This could be due to some connectivity issues.

Using a proxy can help bypass network restrictions that might be preventing access to Twitter. If your setup supports it, you could try using TUN mode.
